
const STOCK_KEY='syldb-stock-v3';
const OLD_OWNED_KEYS=['syldb-owned-v2','syldb-owned-v1','sylveon-owned-v3','sylveon-owned'];
let db=null,cards=[],activeEra='全部',selectedCard=null;
const stock=JSON.parse(localStorage.getItem(STOCK_KEY)||'{}');
const $=s=>document.querySelector(s);
const qty=id=>Math.max(0,Number(stock[id]||0));
const isOwned=c=>qty(c.id)>0;
const save=()=>localStorage.setItem(STOCK_KEY,JSON.stringify(stock));
function migrateOldOwned(){let changed=false;for(const key of OLD_OWNED_KEYS){const raw=JSON.parse(localStorage.getItem(key)||'[]');for(const old of raw){const match=cards.find(c=>old===c.id||String(old).includes(c.card_number));if(match&&qty(match.id)===0){stock[match.id]=1;changed=true}}}if(changed)save()}
async function init(){db=await fetch('master-v30.json?v=3001',{cache:'reload'}).then(r=>r.json());cards=db.cards||[];migrateOldOwned();populateFilters();bindEvents();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker-v30.js?v=3001')}
function populateFilters(){const rs=[...new Set(cards.map(c=>c.rarity).filter(Boolean))].sort();$('#rarityFilter').innerHTML='<option value="all">全部稀有度</option>'+rs.map(r=>`<option value="${esc(r)}">${esc(r)}</option>`).join('')}
function filteredCards(){const q=$('#searchInput').value.trim().toLowerCase(),status=$('#statusFilter').value,rarity=$('#rarityFilter').value;return cards.filter(c=>{const h=`${c.name_ja} ${c.card_number} ${c.set_name} ${c.variant} ${c.rarity}`.toLowerCase();return(!q||h.includes(q))&&(activeEra==='全部'||c.era===activeEra)&&(status==='all'||(status==='owned'&&isOwned(c))||(status==='missing'&&!isOwned(c)))&&(rarity==='all'||c.rarity===rarity)})}
function render(){renderTabs();renderStats();renderCards();renderSummary()}
function renderTabs(){const eras=['全部',...new Set(cards.map(c=>c.era))];$('#eraTabs').innerHTML=eras.map(e=>`<button class="era-tab ${e===activeEra?'active':''}" data-era="${esc(e)}">${esc(e)}</button>`).join('');document.querySelectorAll('.era-tab').forEach(b=>b.onclick=()=>{activeEra=b.dataset.era;render()})}
function renderStats(){const eras=[...new Set(cards.map(c=>c.era))];$('#eraStats').innerHTML=eras.map(e=>{const g=cards.filter(c=>c.era===e),k=g.filter(isOwned).length,t=g.reduce((s,c)=>s+qty(c.id),0);return`<div class="stat-box"><b>${e} ${k}/${g.length}</b><span>库存 ${t} 张</span></div>`}).join('')}
function renderCards(){const arr=filteredCards();$('#emptyState').hidden=arr.length>0;$('#cardGrid').innerHTML=arr.map(c=>`<article class="card ${isOwned(c)?'owned':''}" data-id="${c.id}"><div class="card-visual">${c.image_url?`<img loading="lazy" src="${esc(c.image_url)}" alt="${esc(c.name_ja)}" onload="this.nextElementSibling.hidden=true" onerror="this.remove()">`:''}<div class="card-placeholder">🎀<small>${esc(c.card_number)}</small></div><span class="era-badge">${esc(c.era)}</span><button class="owned-toggle" data-toggle="${c.id}">${qty(c.id)}</button></div><div class="card-body"><div class="card-name">${esc(c.name_ja)}</div><div class="card-number">${esc(c.card_number)}</div><div class="card-meta">${esc(c.set_name)}<br>${esc(c.rarity||'—')} · ${esc(c.variant||'普通版')}</div><div class="card-stock ${qty(c.id)===0?'zero':''}">库存：${qty(c.id)} 张</div></div></article>`).join('');document.querySelectorAll('.owned-toggle').forEach(b=>b.onclick=e=>{e.stopPropagation();changeStock(b.dataset.toggle,1)});document.querySelectorAll('.card').forEach(el=>el.onclick=()=>openDetail(el.dataset.id))}
function renderSummary(){const k=cards.filter(isOwned).length,total=cards.length,t=cards.reduce((s,c)=>s+qty(c.id),0),p=total?Math.round(k/total*100):0;$('#summaryCount').textContent=`${k} / ${total} · 库存 ${t} 张`;$('#summaryPercent').textContent=`${p}%`;$('#progressBar').style.width=`${p}%`}
function changeStock(id,d){stock[id]=Math.max(0,qty(id)+d);if(stock[id]===0)delete stock[id];save();render();if(selectedCard&&selectedCard.id===id)updateModalStock()}
function openDetail(id){selectedCard=cards.find(c=>c.id===id);if(!selectedCard)return;$('#modalVisual').innerHTML=selectedCard.image_url?`<img src="${esc(selectedCard.image_url)}" alt="${esc(selectedCard.name_ja)}">`:'🎀';$('#openOriginalBtn').href=selectedCard.image_url||'#';$('#openOriginalBtn').hidden=!selectedCard.image_url;$('#modalName').textContent=selectedCard.name_ja;$('#modalNumber').textContent=selectedCard.card_number;const meta=[['时代',selectedCard.era],['系列',selectedCard.set_name],['稀有度',selectedCard.rarity||'—'],['版本',selectedCard.variant||'普通版'],['数据库ID',selectedCard.id]];$('#modalMeta').innerHTML=meta.map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('');const src=selectedCard.source_url||'';$('#modalSource').hidden=!src;$('#modalSource').href=src;updateModalStock();$('#detailModal').hidden=false}
function updateModalStock(){if(selectedCard)$('#modalStockCount').textContent=qty(selectedCard.id)}
function bindEvents(){$('#searchInput').oninput=render;$('#statusFilter').onchange=render;$('#rarityFilter').onchange=render;$('#menuBtn').onclick=()=>$('#menuSheet').hidden=false;$('#closeMenuBtn').onclick=()=>$('#menuSheet').hidden=true;$('#menuSheet').onclick=e=>{if(e.target.id==='menuSheet')$('#menuSheet').hidden=true};$('#closeModalBtn').onclick=()=>$('#detailModal').hidden=true;$('#detailModal').onclick=e=>{if(e.target.id==='detailModal')$('#detailModal').hidden=true};$('#plusStockBtn').onclick=()=>changeStock(selectedCard.id,1);$('#minusStockBtn').onclick=()=>changeStock(selectedCard.id,-1);$('#exportBtn').onclick=exportBackup;$('#importFile').onchange=importBackup;$('#migrateBtn').onclick=()=>{migrateOldOwned();render();alert('旧版记录迁移完成')};$('#resetBtn').onclick=()=>{if(confirm('确定清空全部库存记录吗？')){for(const k of Object.keys(stock))delete stock[k];save();render();$('#menuSheet').hidden=true}}}
function exportBackup(){const payload={app:'SYLDB',version:3,exported_at:new Date().toISOString(),stock};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='SYLDB-stock-backup.json';a.click();URL.revokeObjectURL(a.href)}
async function importBackup(e){const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());for(const k of Object.keys(stock))delete stock[k];if(d.stock){for(const[id,n]of Object.entries(d.stock))stock[id]=Math.max(0,Number(n)||0)}else{const ids=d.owned_ids||d.owned||[];ids.forEach(id=>stock[id]=1)}save();render();alert('导入成功');$('#menuSheet').hidden=true}catch{alert('备份文件格式不正确')}}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
init();
